project:
  type: website
  output-dir: docs

# Meta
description-meta: "Meta-researcher MSc, PhD | Supporter of open and reproducible science"
author-meta: "Konstantinos I. Bougioukas"

website:
  title: "Konstantinos I. Bougioukas"
  image: "/files/myprofile.jpeg"
  description: "Meta-researcher MSc, PhD | Supporter of open and reproducible science."
  favicon: "img/logo.png"
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: News
        href: posts.qmd#category=news   
      - text: Visualizations
        href: posts.qmd#category=visualization
      - text: Publications
        menu:
          - text: Highlights
            href: posts.qmd#category=paper
          - text: List of Publications
            href: publications.qmd
#      - text: Teaching
#        href: teach.qmd
      - text: R packages
        href: packages.qmd        
      - text: Posts
        href: posts.qmd
      - text: Links
        href: links.qmd
      - text: Contact
        href: contact.qmd   
    
    right: 
#      - text: CV
#        href: files/bougioukas_CV.pdf 
      - icon: github
        href: https://github.com/bougioukas
#      - icon: twitter 
#        href: https://twitter.com/bugiukas
#      - icon: rss
#        href: posts.xml 
  
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    left: "© Copyright 2024, Konstantinos I. Bougioukas." 
    right:  
      - icon: github
        href: https://github.com/bougioukas/mypage
#      - icon: twitter 
#        href: https://twitter.com/Bugiukas
#      - icon: rss
#        href: posts.xml  
  
  search:
    location: navbar
    type: textbox
  
#  reader-mode: true
  
#  repo-url: https://github.com/bougioukas/bougioukas.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://bougioukas.github.io"
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 1.16em
    linestretch: 1.35
    css: styles.css
    toc: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true
    code-link: false
#    link-external-filter: '^(?:http:|https:)\/\/bougioukas\.github\.io\/custom'
